title: Personal Site
description: A personal site built with Jekyll and deployed on GitHub Pages.
url: "https://shellscribe.github.io"
baseurl: "/personal-site"

theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
